{% set name = "lbcondawrappers" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 285060e890312eec0248ecc1b45f52e91dcf0b596ead8226e916028d56493c8b

build:
  entry_points:
    - lb-conda = LbCondaWrappers:lb_conda
    - lb-conda-dev = LbCondaWrappers:lb_conda_dev
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=61.2
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - lb-telemetry >=0.5.0

test:
  imports:
  #  - LbCondaWrappers
  commands:
    - pip check
    # - lb-conda --help
    # - lb-conda-dev --help
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-core/LbCondaWrappers
  summary: Wrappers for using LHCb CVMFS conda installations
  dev_url: https://gitlab.cern.ch/lhcb-core/LbCondaWrappers
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bcouturi
    - chrisburr
