{% set name = "lbcondawrappers" %}
{% set version = "0.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/LbCondaWrappers-{{ version }}.tar.gz
  sha256: 07e7820dcd704161d45351f6a9e83967e493dc71c3680e1204af67d1166daa36

build:
  number: 0
  noarch: python
  entry_points:
    - lb-conda=LbCondaWrappers:lb_conda
    - lb-conda-dev=LbCondaWrappers:lb_conda_dev
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4,!=3.5
    - setuptools_scm
  run:
    - python !=3.0,!=3.1,!=3.2,!=3.3,!=3.4,!=3.5

test:
  imports:
    - LbCondaWrappers
  commands:
    - pip check
    - lb-conda --help
    - lb-conda-dev --help
  requires:
    - pip

about:
  home: https://gitlab.cern.ch/lhcb-core/tasks/LbCondaWrappers
  summary: Wrappers for using LHCb CVMFS conda installations
  dev_url: https://gitlab.cern.ch/lhcb-core/LbCondaWrappers
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bcouturi
    - chrisburr
